### ISSUE TITLE
Support for musl

### ISSUE THREAD

**Issue by Bun** [sflow/host-sflow#13]
Not all Linux distributions use glibc, support for musl (used by e.g. Alpine) would be great.

So far I've had to make the following adjustments to the source to get it to compile:
- Remove the "backtrace" functionality
- Remove the "malloc_stats" functionality
- Replace `(comparison_fn_t)strcmp` with `(int (*)(const void*, const void*))strcmp` in readDiskCounters

Since these changes mostly remove functionality, I am not sure what the acceptable solution would be in this case.  Maybe simply put some of these features behind `#ifdef __GLIBC__`?  I can submit a trivial patch for this if desired.

**Comment by sflow** [comment]
Yes,   sounds good.  Please submit a pull-request or patch with the minimum changes.

**Comment by Bun** [comment]
FYI, I've been successfully running hsflowd on Alpine 3.4+ for a while now (nflog and pcap) with this patch applied, so consider this resolved.
