### ISSUE TITLE
Dose host sflow follow sflow v5 rfc?

### ISSUE THREAD

**Issue by macauleycheng** [sflow/host-sflow#27]
Because there are many formats which cannot be recognized by logstash sflow plugin or Whireshark. I check the counter polling format value which is different from sflow RFC.
Which collector are suitable for host sflow?

**Comment by sflow** [comment]
The definitive documentation, with all the current extensions,  is here:
https://sflow.org/developers/specifications.php

There is a list of collectors on the same site:
https://sflow.org/products/collectors.php

 but I don't know which of these collectors accept the counter structures from hsflowd today.  Except to say that these collectors (from my company) do:
https://inmon.com/products/index.php
These are commercial products, but sFlowTrend has a free version, and sFlow-RT is free for non-production use:
https://sflow-rt.com/

There is also an sFlow plugin for Ganglia which accepts (only) hsflowd data:
http://ganglia.info/
