### ISSUE TITLE
Centos 8 support

### ISSUE THREAD

**Issue by bigHosting** [sflow/host-sflow#36]
Hi,

Is CentOS 8 supported ? I have tried recompiling https://centos.pkgs.org/7/puias-unsupported-x86_64/hsflowd-1.27.3-1.x86_64.rpm.html but it errors out with iptables netfilter dependency:

make[1]: Leaving directory '/services/nginx/rpmbuild/sd8.com/BUILD/hsflowd-1.27.3/src/json'
PLATFORM=`uname`; \
MYVER=`./getVersion`; \
        MYREL=`./getRelease`; \
        cd src/$PLATFORM; make VERSION=$MYVER RELEASE=$MYREL
make[1]: Entering directory '/services/nginx/rpmbuild/sd8.com/BUILD/hsflowd-1.27.3/src/Linux'
gcc -std=gnu99 -I. -I../sflow -O3 -DNDEBUG -Wall -Wstrict-prototypes -Wunused-value -D_GNU_SOURCE -DHSP_VERSION=1.27.3 -DUTHEAP -DHSF_ULOG -DHSF_JSON -I../json -DHSF_SYSTEM_SLICE -c hsflowconfig.c
In file included from hsflowconfig.c:9:
hsflowd.h:116:10: fatal error: linux/netfilter_ipv4/ipt_ULOG.h: No such file or directory
 #include <linux/netfilter_ipv4/ipt_ULOG.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Thank you

**Comment by bigHosting** [comment]
I realized that:
1. That version I was trying to compile is old
2. The RPM may not be supported

Hence I am closing this ticket because the latest 2.0.26 -3 compiles cleanly on CentOS 8.1
Thank you

**Comment by sflow** [comment]
I added a binary download for Centos8 on https://sflow.net,  and a Docker build so you can run "./docker_build_on centos8" in future.

**Comment by bigHosting** [comment]
Thank you, I've tested it and works well!
