### ISSUE TITLE
No ulog/nflog sampling on arm7

### ISSUE THREAD

**Issue by lspgn** [sflow/host-sflow#39]
Hello,
I managed to build hsflowd on arm7 for my Raspberry pi using Docker ubuntu:18.04. I tried to configure nflog sampling but it fails (pcap sampling works fine).

```
$ sudo hsflowd -dddd -f ./hsflowd.conf
[...]
dbg1: dlopen(/etc/hsflowd/modules/mod_nflog.so) failed : /etc/hsflowd/modules/mod_nflog.so: undefined symbol: __aeabi_uidiv
dlsym(mod_nflog) failed : hsflowd: undefined symbol: mod_nflog
[...]
```

```
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
```

I *think* since it was built on a fully-functional OS, the RPI is missing some functions. Managed to find some [doc](https://www.raspberrypi.org/forums/viewtopic.php?t=75845).
Not sure how to proceed though if I can force a specific GCC (`arm-eabi-none-gcc` vs `arm-eabi-gcc`?).

Thank you for your help

**Comment by sflow** [comment]
Looks like it might be related to this one?
https://stackoverflow.com/questions/6576517/what-is-the-cause-of-not-being-able-to-divide-numbers-in-gcc
