### ISSUE TITLE
Version 2.0.50-3 not compatible with Debian 10

### ISSUE THREAD

**Issue by MiniPierre** [sflow/host-sflow#51]
The last version introduces INET_DIAG_SOCKOPTn, with came up with the 5.10 Linux kernel version. Howerver, the buster repository is stuck at 4.19 (https://packages.debian.org/buster/linux-image-amd64), thus the compilation fails.
```
mod_tcp.c: In function 'parse_diag_msg':
mod_tcp.c:256:7: error: 'INET_DIAG_SOCKOPT' undeclared (first use in this function); did you mean 'INET_DIAG_LOCALS'?
  case INET_DIAG_SOCKOPT: {
       ^~~~~~~~~~~~~~~~~
       INET_DIAG_LOCALS
mod_tcp.c:256:7: note: each undeclared identifier is reported only once for each function it appears in
```
Could you make it compatible with older kernel versions ?

**Comment by sflow** [comment]
That was clumsy of me,  sorry.   This change should be all you need:
https://github.com/sflow/host-sflow/commit/a4631a84b710b5033340fff2b6bf359cc57b24fa
I'll probably do a 2.0.50-4 release with this later today.
