### ISSUE TITLE
Question for the sampling rate

### ISSUE THREAD

**Issue by luocooong** [sflow/host-sflow#53]
Hi, thank you for your great open source. Then I found a question unable to get the answer on docs, like the following list:
1. How do I set the sampling rate to 100% (or 1-in-N)? because I used the snippet(`sampling = 1`) and it's not working.
2. How do I understand the log infos of sampling? `"SamplingRate":1000,"SamplePool":9000`

There are full settings:
```
agent.cidr = 192.168.0.0/16
polling = 60
sampling = 1
collector { ip=127.0.0.1 udpport=6343 }
pcap { speed = 1- }
tcp { }
```

**Comment by luocooong** [comment]
@sflow Hi, It finally worked(set the samping.SPEED = 1), `1:1` ratio only applies to the test, thank you. And then, there are some questions for the project:
1. What is the technical principle of hsflow project capture the sflow protocol? Is there an performance impact on the host?
2. How do I understand the data fields of the sflow (special reference to the sflow protocol)?
3. Is it possible to provide an armv8-based version in the next release?

**Comment by sflow** [comment]
(1) sFlow is designed to run continuously on all servers and network switches.  The sampling rate can be adjusted to make sure that there is no performance impact.  The goal is to provide essential visibility even when (especially when) the system is under pressure.
(2) For a low-level example of decoding the XDR-formatted output see the sflowtool project. The spec is held at https://sflow.org.  For examples and discussion see https://blog.sflow.com and GoogleGroups:sFlow.  To understand what is possible on the analytics side you might experiment with sFlow-RT.
(3) I believe the current hsflowd sources can be compiled on ARM?  Please raise an issue if that doesn't work.
